version: '3.6'

services:
        geomatics_database:
                image: mysql/mysql-server
                container_name: geomatics-database
                networks:
                        - internal-network
                environment:
                        MYSQL_DATABASE: geomatics_database
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_ROOT_HOST: '%'
                volumes:
                        - ./init:/docker-entrypoint-initdb.d/:ro
#                        - /home/kschuma/projects/geomatics/database/init:/docker-entrypoint-initdb.d/:ro
networks:
        internal-network:
                name: geomatics
